name: TempFly
main: com.moneybags.tempfly.TempFly
softdepend: [ASkyBlock, Essentials, MVdWPlaceholderAPI, PlaceholderAPI, aSkyBlock, Vault]
api-version: 1.13
version: 2.0.2
commands:
    tempfly:
        description: base command
        aliases: [tfly, tf]