name: TempFly
main: com.moneybags.tempfly.TempFly
softdepend: [Factions, ASkyBlock, Essentials, MVdWPlaceholderAPI, PlaceholderAPI, aSkyBlock, Vault, WorldGuard, WorldEdit, IridiumSkyblock, BentoBox, SuperiorSkyblock2]
api-version: 1.13
version: 3.1.7
commands:
    tempfly:
        description: base command
        aliases: [tfly, tf]